### ISSUE TITLE
Wherever user is writing to their story, call it private journal.

### ISSUE THREAD

**Issue by 1geek0** [1geek0/neuro-frontend#12]
Make it clear with supporting text that this information always stays private.

We could colour code public and private elements to make it explicit

**Comment by Ramshankar07** [comment]
![Screenshot (449)](https://github.com/user-attachments/assets/a70b46c0-f38b-47c7-aba2-1f9167c10048)
I

**Comment by Ramshankar07** [comment]
I have added a note and this lock icon, so that it will be good, Reply here if it good or still needs to change it green, red colour

**Comment by 1geek0** [comment]
Make the logo green

**Comment by Ramshankar07** [comment]
Which logo? u mean the lock ?

**Comment by 1geek0** [comment]
Yes

**Comment by Ramshankar07** [comment]
ref Chore: Adding private elements to make it explicit #15
