### ISSUE TITLE
All stories editable by every user

### ISSUE THREAD

**Issue by saineshnakra** [1geek0/neuro-frontend#32]
All the stories are editable for all. Should be fixed and not be editable for all

**Comment by saineshnakra** [comment]
Simple thing, we have to remove delete all button, add a delete button to each story and while fetching we just need to update the query to pull stories attached to the userid.

**Comment by manasgoel2002** [comment]
I think the user authentication data is missing in src/app/api/stories/route.ts. That’s why it allows the deletion of all stories.
