### ISSUE TITLE
Implement Discourse for community

### ISSUE THREAD

**Issue by 1geek0** [1geek0/neuro-frontend#4]
Our users should be able to talk about their story with meningioma on our platform.
This helps them as well as others make better decisions, specially ones related to quality of life that may not be medical.
For example, [hypothetical] some patients might get headache from eating certain nuts and by sharing this other patients could offer advice or their experience if they've experienced something similar.

To do this, we will use [discourse](https://discourse.org). This makes it much easier to have a forum interface without building and maintaining it ourselves.

Our community is setup at https://neuro86.discourse.group. Ask @1geek0 for admin account credentials to start managing

**Comment by Ramshankar07** [comment]
Should I add it in /home or can we have a button like a navbar to redirect to forum and also for their account to store their stories?
